name: Bump version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Bump version
        id: bump
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version patch
          echo "New version: $(node -p "require('./package.json').version")"
          git push

      - name: Publish to npm
        run: npm publish --access public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
    